### ISSUE TITLE
Query about GPC source code 

### ISSUE THREAD

**Issue by Gthq** [bamert/openGPC#1]
1. When I tried to run this code. Something wrong occured. "SET" in the cmakelists should be write as `SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -O3  -mavx2 -march=core-avx2   -pthread -funroll-loops")` if you see "undefined reference to thread_create"

2. By the way, how can I run "sparsematch"? I clicked it but nothing happened.  Please.

Thank you for your works in GPC, I'm very interested in this work and want more informations about  it.

**Comment by bamert** [comment]
Hi Gthq,

1. Thanks for the pointer, added the flag.
2. sparsematch is run from the command line with the arguments forest path, left image path, right image path.
The estimated disparities are visualized overlaid on the input image and output as disparity.png (see sparsematch.cpp).
Any rectified stereo image pair will work together with one of the pre-trained random forests supplied in the subdirectory /forest.

Running without arguments will evaluate a default case assuming the kitti 2012 stereo dataset is present within /data. In the default case,  the ../../forests/defaultZeroForest.txt pre-trained forest will be used.
